### PR TITLE
UI improvements for the list:routes command. Both the pretty output and the table output

### PR DESCRIPTION
**Pull request by thetutlage**
> WARNING: The code is bit unorganised right now. If we are all good with the UI changes, then I will cleanup the code.

## Summary of changes
This PR targets to fix the following items.

- Test the colors on both light and dark themes, including solarized light.
- Make verbose output look a bit more organized. Did this using lines to render middleware ( screenshot will help visualize )
- Make the table output respect the terminal width as well. Why abandon it, when we can fix it :)

I will be posting screenshots as multiple comments

### CODE REVIEW

**Comment by thetutlage** [comment]
## New color scheme for dark and light themes

### Light theme

new-light-theme

### Solarized theme

new-solarized-theme

### Dark theme

new-pretty-list

**Comment by thetutlage** [comment]
## Old vs new pretty output

### Old pretty output

old-pretty-list

### New pretty output

new-pretty-list

### Old pretty verbose output

old-pretty-list-verbose

### New pretty verbose output

new-pretty-list-verbose

**Comment by thetutlage** [comment]
## Old vs new table output

### Old table output (small terminal width)

old-table-small-width

### New table output (small terminal width)

new-table-output

**Review by Julien-R44 — APPROVED** [review]
Pretty list routes is now even more prettier ! 

This was the final polish we needed, it seems perfect now. Thanks!

**Comment by RomainLanz** [comment]
The screenshots look good!

For the verbose output, could we use `˪` for the latest middleware, or does this add too much-unwanted logic?

**Comment by thetutlage** [comment]
> The screenshots look good!
> 
> For the verbose output, could we use `˪` for the latest middleware, or does this add too much-unwanted logic?
> 

Yeah, we can

**Pull request merged**
